# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += rzpi-ext-i2c.dtbo
dtb-y += rzpi-ext-spi.dtbo
dtb-y += rzpi-can.dtbo
dtb-y += rzpi-ov5640.dtbo
dtb-y += rzpi-dsi.dtbo
