# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-$(CONFIG_ARCH_R9A07G044) += rzg2l-sbc-ext-i2c.dtbo
dtb-$(CONFIG_ARCH_R9A07G044) += rzg2l-sbc-ext-spi.dtbo
dtb-$(CONFIG_ARCH_R9A07G044) += rzg2l-sbc-can.dtbo
dtb-$(CONFIG_ARCH_R9A07G044) += rzg2l-sbc-ov5640.dtbo
dtb-$(CONFIG_ARCH_R9A07G044) += rzg2l-sbc-dsi.dtbo
dtb-$(CONFIG_ARCH_R9A09G057) += rzv2h-rdk-ext-i2c.dtbo
dtb-$(CONFIG_ARCH_R9A09G057) += rzv2h-rdk-ext-sci.dtbo
dtb-$(CONFIG_ARCH_R9A09G057) += rzv2h-rdk-ext-spi.dtbo
