# SPDX-License-Identifier: GPL-2.0

# required for overlay support
DTC_FLAGS += -@

dtb-y += rzg2l-sbc-ext-i2c.dtbo
dtb-y += rzg2l-sbc-ext-spi.dtbo
dtb-y += rzg2l-sbc-can.dtbo
dtb-y += rzg2l-sbc-ov5640.dtbo
dtb-y += rzg2l-sbc-dsi.dtbo
