# SPDX-License-Identifier: GPL-2.0
ap1302-objs	:= \
		ap1302-core.o \
		ap1302-debug.o \
		ap1302-fw.o \
		ap1302-spi.o \
		ap1302-sysfs.o \
		ap1302-v4l2ctrls.o

obj-$(CONFIG_VIDEO_AP1302)	+= ap1302.o